In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

## Verify the results from NL-Python agent

In [8]:
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df['species'] = iris.target_names[iris.target]

iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2,virginica
146,6.3,2.5,5.0,1.9,2,virginica
147,6.5,3.0,5.2,2.0,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica
149,5.9,3.0,5.1,1.8,2,virginica

In [9]:
iris_df[iris_df['petal width (cm)'] > 2]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
100,6.3,3.3,6.0,2.5,2,virginica
102,7.1,3.0,5.9,2.1,2,virginica
104,6.5,3.0,5.8,2.2,2,virginica
105,7.6,3.0,6.6,2.1,2,virginica
109,7.2,3.6,6.1,2.5,2,virginica
112,6.8,3.0,5.5,2.1,2,virginica
114,5.8,2.8,5.1,2.4,2,virginica
115,6.4,3.2,5.3,2.3,2,virginica
117,7.7,3.8,6.7,2.2,2,virginica
118,7.7,2.6,6.9,2.3,2,virginica
120,6.9,3.2,5.7,2.3,2,virginica
124,6.7,3.3,5.7,2.1,2,virginica
128,6.4,2.8,5.6,2.1,2,virginica
132,6.4,2.8,5.6,2.2,2,virginica
135,7.7,3.0,6.1,2.3,2,virginica
136,6.3,3.4,5.6,2.4,2,virginica
139,6.9,3.1,5.4,2.1,2,virginica
140,6.7,3.1,5.6,2.4,2,virginica
141,6.9,3.1,5.1,2.3,2,virginica
143,6.8,3.2,5.9,2.3,2,virginica
144,6.7,3.3,5.7,2.5,2,virginica
145,6.7,3.0,5.2,2.3,2,virginica
148,6.2,3.4,5.4,2.3,2,virginica

In [12]:
iris_df[iris_df['petal width (cm)'] > 2].select_dtypes(include=[np.number]).mean()
iris_df.select_dtypes(include=[np.number]).mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
target               1.000000
dtype: float64